packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@base-ui/react': ^1.6.0
  '@cloudflare/workers-types': ^5.20260801.1
  '@effect/platform-node': 4.0.0-beta.102
  '@types/node': ^24
  alchemy: 2.0.0-beta.67
  better-auth: ^1.6.25
  class-variance-authority: ^0.7.1
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  effect: 4.0.0-beta.102
  lucide-react: ^0.539.0
  shadcn: ^3.8.5
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
minimumReleaseAgeExclude:
  - hono@4.13.0
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  msw: false
  sharp: true
  workerd: true
